package com.ew.autofly.db.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 11): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 11;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        EPointDao.createTable(db, ifNotExists);
        FlightRecordDao.createTable(db, ifNotExists);
        FlightRecordDetailDao.createTable(db, ifNotExists);
        MissionBatchDao.createTable(db, ifNotExists);
        MissionBeltOrthoPatrolDao.createTable(db, ifNotExists);
        MissionChannelPatrolDao.createTable(db, ifNotExists);
        MissionFinePatrolDao.createTable(db, ifNotExists);
        MissionPhotoDao.createTable(db, ifNotExists);
        MissionPointCloudDao.createTable(db, ifNotExists);
        MissionPointCloudV2Dao.createTable(db, ifNotExists);
        MissionTowerDao.createTable(db, ifNotExists);
        MissionTreeObstacleDao.createTable(db, ifNotExists);
        MultiSpectralMissionConfigDao.createTable(db, ifNotExists);
        PatrolSubJobExecuteStatusDbDao.createTable(db, ifNotExists);
        TowerGridLineDao.createTable(db, ifNotExists);
        TowerLocationUpdateDao.createTable(db, ifNotExists);
        TowerStudyComponentDao.createTable(db, ifNotExists);
        TowerStudyDetailDao.createTable(db, ifNotExists);
        TowerStudyDetailV2Dao.createTable(db, ifNotExists);
        TowerStudyRecordDao.createTable(db, ifNotExists);
        FlyPointActionDao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        EPointDao.dropTable(db, ifExists);
        FlightRecordDao.dropTable(db, ifExists);
        FlightRecordDetailDao.dropTable(db, ifExists);
        MissionBatchDao.dropTable(db, ifExists);
        MissionBeltOrthoPatrolDao.dropTable(db, ifExists);
        MissionChannelPatrolDao.dropTable(db, ifExists);
        MissionFinePatrolDao.dropTable(db, ifExists);
        MissionPhotoDao.dropTable(db, ifExists);
        MissionPointCloudDao.dropTable(db, ifExists);
        MissionPointCloudV2Dao.dropTable(db, ifExists);
        MissionTowerDao.dropTable(db, ifExists);
        MissionTreeObstacleDao.dropTable(db, ifExists);
        MultiSpectralMissionConfigDao.dropTable(db, ifExists);
        PatrolSubJobExecuteStatusDbDao.dropTable(db, ifExists);
        TowerGridLineDao.dropTable(db, ifExists);
        TowerLocationUpdateDao.dropTable(db, ifExists);
        TowerStudyComponentDao.dropTable(db, ifExists);
        TowerStudyDetailDao.dropTable(db, ifExists);
        TowerStudyDetailV2Dao.dropTable(db, ifExists);
        TowerStudyRecordDao.dropTable(db, ifExists);
        FlyPointActionDao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(EPointDao.class);
        registerDaoClass(FlightRecordDao.class);
        registerDaoClass(FlightRecordDetailDao.class);
        registerDaoClass(MissionBatchDao.class);
        registerDaoClass(MissionBeltOrthoPatrolDao.class);
        registerDaoClass(MissionChannelPatrolDao.class);
        registerDaoClass(MissionFinePatrolDao.class);
        registerDaoClass(MissionPhotoDao.class);
        registerDaoClass(MissionPointCloudDao.class);
        registerDaoClass(MissionPointCloudV2Dao.class);
        registerDaoClass(MissionTowerDao.class);
        registerDaoClass(MissionTreeObstacleDao.class);
        registerDaoClass(MultiSpectralMissionConfigDao.class);
        registerDaoClass(PatrolSubJobExecuteStatusDbDao.class);
        registerDaoClass(TowerGridLineDao.class);
        registerDaoClass(TowerLocationUpdateDao.class);
        registerDaoClass(TowerStudyComponentDao.class);
        registerDaoClass(TowerStudyDetailDao.class);
        registerDaoClass(TowerStudyDetailV2Dao.class);
        registerDaoClass(TowerStudyRecordDao.class);
        registerDaoClass(FlyPointActionDao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

}
