package com.ew.autofly.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.ew.autofly.db.entity.EPoint;
import com.ew.autofly.db.entity.FlightRecord;
import com.ew.autofly.db.entity.FlightRecordDetail;
import com.ew.autofly.db.entity.MissionBatch;
import com.ew.autofly.db.entity.MissionBeltOrthoPatrol;
import com.ew.autofly.db.entity.MissionChannelPatrol;
import com.ew.autofly.db.entity.MissionFinePatrol;
import com.ew.autofly.db.entity.MissionPhoto;
import com.ew.autofly.db.entity.MissionPointCloud;
import com.ew.autofly.db.entity.MissionPointCloudV2;
import com.ew.autofly.db.entity.MissionTower;
import com.ew.autofly.db.entity.MissionTreeObstacle;
import com.ew.autofly.db.entity.MultiSpectralMissionConfig;
import com.ew.autofly.db.entity.PatrolSubJobExecuteStatusDb;
import com.ew.autofly.db.entity.TowerGridLine;
import com.ew.autofly.db.entity.TowerLocationUpdate;
import com.ew.autofly.db.entity.TowerStudyComponent;
import com.ew.autofly.db.entity.TowerStudyDetail;
import com.ew.autofly.db.entity.TowerStudyDetailV2;
import com.ew.autofly.db.entity.TowerStudyRecord;
import com.ew.autofly.mode.linepatrol.point.ui.model.FlyPointAction;

import com.ew.autofly.db.dao.EPointDao;
import com.ew.autofly.db.dao.FlightRecordDao;
import com.ew.autofly.db.dao.FlightRecordDetailDao;
import com.ew.autofly.db.dao.MissionBatchDao;
import com.ew.autofly.db.dao.MissionBeltOrthoPatrolDao;
import com.ew.autofly.db.dao.MissionChannelPatrolDao;
import com.ew.autofly.db.dao.MissionFinePatrolDao;
import com.ew.autofly.db.dao.MissionPhotoDao;
import com.ew.autofly.db.dao.MissionPointCloudDao;
import com.ew.autofly.db.dao.MissionPointCloudV2Dao;
import com.ew.autofly.db.dao.MissionTowerDao;
import com.ew.autofly.db.dao.MissionTreeObstacleDao;
import com.ew.autofly.db.dao.MultiSpectralMissionConfigDao;
import com.ew.autofly.db.dao.PatrolSubJobExecuteStatusDbDao;
import com.ew.autofly.db.dao.TowerGridLineDao;
import com.ew.autofly.db.dao.TowerLocationUpdateDao;
import com.ew.autofly.db.dao.TowerStudyComponentDao;
import com.ew.autofly.db.dao.TowerStudyDetailDao;
import com.ew.autofly.db.dao.TowerStudyDetailV2Dao;
import com.ew.autofly.db.dao.TowerStudyRecordDao;
import com.ew.autofly.db.dao.FlyPointActionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig ePointDaoConfig;
    private final DaoConfig flightRecordDaoConfig;
    private final DaoConfig flightRecordDetailDaoConfig;
    private final DaoConfig missionBatchDaoConfig;
    private final DaoConfig missionBeltOrthoPatrolDaoConfig;
    private final DaoConfig missionChannelPatrolDaoConfig;
    private final DaoConfig missionFinePatrolDaoConfig;
    private final DaoConfig missionPhotoDaoConfig;
    private final DaoConfig missionPointCloudDaoConfig;
    private final DaoConfig missionPointCloudV2DaoConfig;
    private final DaoConfig missionTowerDaoConfig;
    private final DaoConfig missionTreeObstacleDaoConfig;
    private final DaoConfig multiSpectralMissionConfigDaoConfig;
    private final DaoConfig patrolSubJobExecuteStatusDbDaoConfig;
    private final DaoConfig towerGridLineDaoConfig;
    private final DaoConfig towerLocationUpdateDaoConfig;
    private final DaoConfig towerStudyComponentDaoConfig;
    private final DaoConfig towerStudyDetailDaoConfig;
    private final DaoConfig towerStudyDetailV2DaoConfig;
    private final DaoConfig towerStudyRecordDaoConfig;
    private final DaoConfig flyPointActionDaoConfig;

    private final EPointDao ePointDao;
    private final FlightRecordDao flightRecordDao;
    private final FlightRecordDetailDao flightRecordDetailDao;
    private final MissionBatchDao missionBatchDao;
    private final MissionBeltOrthoPatrolDao missionBeltOrthoPatrolDao;
    private final MissionChannelPatrolDao missionChannelPatrolDao;
    private final MissionFinePatrolDao missionFinePatrolDao;
    private final MissionPhotoDao missionPhotoDao;
    private final MissionPointCloudDao missionPointCloudDao;
    private final MissionPointCloudV2Dao missionPointCloudV2Dao;
    private final MissionTowerDao missionTowerDao;
    private final MissionTreeObstacleDao missionTreeObstacleDao;
    private final MultiSpectralMissionConfigDao multiSpectralMissionConfigDao;
    private final PatrolSubJobExecuteStatusDbDao patrolSubJobExecuteStatusDbDao;
    private final TowerGridLineDao towerGridLineDao;
    private final TowerLocationUpdateDao towerLocationUpdateDao;
    private final TowerStudyComponentDao towerStudyComponentDao;
    private final TowerStudyDetailDao towerStudyDetailDao;
    private final TowerStudyDetailV2Dao towerStudyDetailV2Dao;
    private final TowerStudyRecordDao towerStudyRecordDao;
    private final FlyPointActionDao flyPointActionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        ePointDaoConfig = daoConfigMap.get(EPointDao.class).clone();
        ePointDaoConfig.initIdentityScope(type);

        flightRecordDaoConfig = daoConfigMap.get(FlightRecordDao.class).clone();
        flightRecordDaoConfig.initIdentityScope(type);

        flightRecordDetailDaoConfig = daoConfigMap.get(FlightRecordDetailDao.class).clone();
        flightRecordDetailDaoConfig.initIdentityScope(type);

        missionBatchDaoConfig = daoConfigMap.get(MissionBatchDao.class).clone();
        missionBatchDaoConfig.initIdentityScope(type);

        missionBeltOrthoPatrolDaoConfig = daoConfigMap.get(MissionBeltOrthoPatrolDao.class).clone();
        missionBeltOrthoPatrolDaoConfig.initIdentityScope(type);

        missionChannelPatrolDaoConfig = daoConfigMap.get(MissionChannelPatrolDao.class).clone();
        missionChannelPatrolDaoConfig.initIdentityScope(type);

        missionFinePatrolDaoConfig = daoConfigMap.get(MissionFinePatrolDao.class).clone();
        missionFinePatrolDaoConfig.initIdentityScope(type);

        missionPhotoDaoConfig = daoConfigMap.get(MissionPhotoDao.class).clone();
        missionPhotoDaoConfig.initIdentityScope(type);

        missionPointCloudDaoConfig = daoConfigMap.get(MissionPointCloudDao.class).clone();
        missionPointCloudDaoConfig.initIdentityScope(type);

        missionPointCloudV2DaoConfig = daoConfigMap.get(MissionPointCloudV2Dao.class).clone();
        missionPointCloudV2DaoConfig.initIdentityScope(type);

        missionTowerDaoConfig = daoConfigMap.get(MissionTowerDao.class).clone();
        missionTowerDaoConfig.initIdentityScope(type);

        missionTreeObstacleDaoConfig = daoConfigMap.get(MissionTreeObstacleDao.class).clone();
        missionTreeObstacleDaoConfig.initIdentityScope(type);

        multiSpectralMissionConfigDaoConfig = daoConfigMap.get(MultiSpectralMissionConfigDao.class).clone();
        multiSpectralMissionConfigDaoConfig.initIdentityScope(type);

        patrolSubJobExecuteStatusDbDaoConfig = daoConfigMap.get(PatrolSubJobExecuteStatusDbDao.class).clone();
        patrolSubJobExecuteStatusDbDaoConfig.initIdentityScope(type);

        towerGridLineDaoConfig = daoConfigMap.get(TowerGridLineDao.class).clone();
        towerGridLineDaoConfig.initIdentityScope(type);

        towerLocationUpdateDaoConfig = daoConfigMap.get(TowerLocationUpdateDao.class).clone();
        towerLocationUpdateDaoConfig.initIdentityScope(type);

        towerStudyComponentDaoConfig = daoConfigMap.get(TowerStudyComponentDao.class).clone();
        towerStudyComponentDaoConfig.initIdentityScope(type);

        towerStudyDetailDaoConfig = daoConfigMap.get(TowerStudyDetailDao.class).clone();
        towerStudyDetailDaoConfig.initIdentityScope(type);

        towerStudyDetailV2DaoConfig = daoConfigMap.get(TowerStudyDetailV2Dao.class).clone();
        towerStudyDetailV2DaoConfig.initIdentityScope(type);

        towerStudyRecordDaoConfig = daoConfigMap.get(TowerStudyRecordDao.class).clone();
        towerStudyRecordDaoConfig.initIdentityScope(type);

        flyPointActionDaoConfig = daoConfigMap.get(FlyPointActionDao.class).clone();
        flyPointActionDaoConfig.initIdentityScope(type);

        ePointDao = new EPointDao(ePointDaoConfig, this);
        flightRecordDao = new FlightRecordDao(flightRecordDaoConfig, this);
        flightRecordDetailDao = new FlightRecordDetailDao(flightRecordDetailDaoConfig, this);
        missionBatchDao = new MissionBatchDao(missionBatchDaoConfig, this);
        missionBeltOrthoPatrolDao = new MissionBeltOrthoPatrolDao(missionBeltOrthoPatrolDaoConfig, this);
        missionChannelPatrolDao = new MissionChannelPatrolDao(missionChannelPatrolDaoConfig, this);
        missionFinePatrolDao = new MissionFinePatrolDao(missionFinePatrolDaoConfig, this);
        missionPhotoDao = new MissionPhotoDao(missionPhotoDaoConfig, this);
        missionPointCloudDao = new MissionPointCloudDao(missionPointCloudDaoConfig, this);
        missionPointCloudV2Dao = new MissionPointCloudV2Dao(missionPointCloudV2DaoConfig, this);
        missionTowerDao = new MissionTowerDao(missionTowerDaoConfig, this);
        missionTreeObstacleDao = new MissionTreeObstacleDao(missionTreeObstacleDaoConfig, this);
        multiSpectralMissionConfigDao = new MultiSpectralMissionConfigDao(multiSpectralMissionConfigDaoConfig, this);
        patrolSubJobExecuteStatusDbDao = new PatrolSubJobExecuteStatusDbDao(patrolSubJobExecuteStatusDbDaoConfig, this);
        towerGridLineDao = new TowerGridLineDao(towerGridLineDaoConfig, this);
        towerLocationUpdateDao = new TowerLocationUpdateDao(towerLocationUpdateDaoConfig, this);
        towerStudyComponentDao = new TowerStudyComponentDao(towerStudyComponentDaoConfig, this);
        towerStudyDetailDao = new TowerStudyDetailDao(towerStudyDetailDaoConfig, this);
        towerStudyDetailV2Dao = new TowerStudyDetailV2Dao(towerStudyDetailV2DaoConfig, this);
        towerStudyRecordDao = new TowerStudyRecordDao(towerStudyRecordDaoConfig, this);
        flyPointActionDao = new FlyPointActionDao(flyPointActionDaoConfig, this);

        registerDao(EPoint.class, ePointDao);
        registerDao(FlightRecord.class, flightRecordDao);
        registerDao(FlightRecordDetail.class, flightRecordDetailDao);
        registerDao(MissionBatch.class, missionBatchDao);
        registerDao(MissionBeltOrthoPatrol.class, missionBeltOrthoPatrolDao);
        registerDao(MissionChannelPatrol.class, missionChannelPatrolDao);
        registerDao(MissionFinePatrol.class, missionFinePatrolDao);
        registerDao(MissionPhoto.class, missionPhotoDao);
        registerDao(MissionPointCloud.class, missionPointCloudDao);
        registerDao(MissionPointCloudV2.class, missionPointCloudV2Dao);
        registerDao(MissionTower.class, missionTowerDao);
        registerDao(MissionTreeObstacle.class, missionTreeObstacleDao);
        registerDao(MultiSpectralMissionConfig.class, multiSpectralMissionConfigDao);
        registerDao(PatrolSubJobExecuteStatusDb.class, patrolSubJobExecuteStatusDbDao);
        registerDao(TowerGridLine.class, towerGridLineDao);
        registerDao(TowerLocationUpdate.class, towerLocationUpdateDao);
        registerDao(TowerStudyComponent.class, towerStudyComponentDao);
        registerDao(TowerStudyDetail.class, towerStudyDetailDao);
        registerDao(TowerStudyDetailV2.class, towerStudyDetailV2Dao);
        registerDao(TowerStudyRecord.class, towerStudyRecordDao);
        registerDao(FlyPointAction.class, flyPointActionDao);
    }
    
    public void clear() {
        ePointDaoConfig.clearIdentityScope();
        flightRecordDaoConfig.clearIdentityScope();
        flightRecordDetailDaoConfig.clearIdentityScope();
        missionBatchDaoConfig.clearIdentityScope();
        missionBeltOrthoPatrolDaoConfig.clearIdentityScope();
        missionChannelPatrolDaoConfig.clearIdentityScope();
        missionFinePatrolDaoConfig.clearIdentityScope();
        missionPhotoDaoConfig.clearIdentityScope();
        missionPointCloudDaoConfig.clearIdentityScope();
        missionPointCloudV2DaoConfig.clearIdentityScope();
        missionTowerDaoConfig.clearIdentityScope();
        missionTreeObstacleDaoConfig.clearIdentityScope();
        multiSpectralMissionConfigDaoConfig.clearIdentityScope();
        patrolSubJobExecuteStatusDbDaoConfig.clearIdentityScope();
        towerGridLineDaoConfig.clearIdentityScope();
        towerLocationUpdateDaoConfig.clearIdentityScope();
        towerStudyComponentDaoConfig.clearIdentityScope();
        towerStudyDetailDaoConfig.clearIdentityScope();
        towerStudyDetailV2DaoConfig.clearIdentityScope();
        towerStudyRecordDaoConfig.clearIdentityScope();
        flyPointActionDaoConfig.clearIdentityScope();
    }

    public EPointDao getEPointDao() {
        return ePointDao;
    }

    public FlightRecordDao getFlightRecordDao() {
        return flightRecordDao;
    }

    public FlightRecordDetailDao getFlightRecordDetailDao() {
        return flightRecordDetailDao;
    }

    public MissionBatchDao getMissionBatchDao() {
        return missionBatchDao;
    }

    public MissionBeltOrthoPatrolDao getMissionBeltOrthoPatrolDao() {
        return missionBeltOrthoPatrolDao;
    }

    public MissionChannelPatrolDao getMissionChannelPatrolDao() {
        return missionChannelPatrolDao;
    }

    public MissionFinePatrolDao getMissionFinePatrolDao() {
        return missionFinePatrolDao;
    }

    public MissionPhotoDao getMissionPhotoDao() {
        return missionPhotoDao;
    }

    public MissionPointCloudDao getMissionPointCloudDao() {
        return missionPointCloudDao;
    }

    public MissionPointCloudV2Dao getMissionPointCloudV2Dao() {
        return missionPointCloudV2Dao;
    }

    public MissionTowerDao getMissionTowerDao() {
        return missionTowerDao;
    }

    public MissionTreeObstacleDao getMissionTreeObstacleDao() {
        return missionTreeObstacleDao;
    }

    public MultiSpectralMissionConfigDao getMultiSpectralMissionConfigDao() {
        return multiSpectralMissionConfigDao;
    }

    public PatrolSubJobExecuteStatusDbDao getPatrolSubJobExecuteStatusDbDao() {
        return patrolSubJobExecuteStatusDbDao;
    }

    public TowerGridLineDao getTowerGridLineDao() {
        return towerGridLineDao;
    }

    public TowerLocationUpdateDao getTowerLocationUpdateDao() {
        return towerLocationUpdateDao;
    }

    public TowerStudyComponentDao getTowerStudyComponentDao() {
        return towerStudyComponentDao;
    }

    public TowerStudyDetailDao getTowerStudyDetailDao() {
        return towerStudyDetailDao;
    }

    public TowerStudyDetailV2Dao getTowerStudyDetailV2Dao() {
        return towerStudyDetailV2Dao;
    }

    public TowerStudyRecordDao getTowerStudyRecordDao() {
        return towerStudyRecordDao;
    }

    public FlyPointActionDao getFlyPointActionDao() {
        return flyPointActionDao;
    }

}
