package com.ew.autofly.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.ew.autofly.db.entity.PatrolSubJobExecuteStatusDb;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "patrol_subjob_execute_status".
*/
public class PatrolSubJobExecuteStatusDbDao extends AbstractDao<PatrolSubJobExecuteStatusDb, Long> {

    public static final String TABLENAME = "patrol_subjob_execute_status";

    /**
     * Properties of entity PatrolSubJobExecuteStatusDb.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MissionId = new Property(1, long.class, "missionId", false, "MISSION_ID");
        public final static Property Status = new Property(2, int.class, "status", false, "STATUS");
    }


    public PatrolSubJobExecuteStatusDbDao(DaoConfig config) {
        super(config);
    }
    
    public PatrolSubJobExecuteStatusDbDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"patrol_subjob_execute_status\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"MISSION_ID\" INTEGER NOT NULL ," + // 1: missionId
                "\"STATUS\" INTEGER NOT NULL );"); // 2: status
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"patrol_subjob_execute_status\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PatrolSubJobExecuteStatusDb entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getMissionId());
        stmt.bindLong(3, entity.getStatus());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PatrolSubJobExecuteStatusDb entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getMissionId());
        stmt.bindLong(3, entity.getStatus());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PatrolSubJobExecuteStatusDb readEntity(Cursor cursor, int offset) {
        PatrolSubJobExecuteStatusDb entity = new PatrolSubJobExecuteStatusDb( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // missionId
            cursor.getInt(offset + 2) // status
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PatrolSubJobExecuteStatusDb entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMissionId(cursor.getLong(offset + 1));
        entity.setStatus(cursor.getInt(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PatrolSubJobExecuteStatusDb entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PatrolSubJobExecuteStatusDb entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PatrolSubJobExecuteStatusDb entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
