package com.ew.autofly.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.ew.autofly.db.entity.TowerStudyComponent;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "t_Tower_StudyComponent".
*/
public class TowerStudyComponentDao extends AbstractDao<TowerStudyComponent, Long> {

    public static final String TABLENAME = "t_Tower_StudyComponent";

    /**
     * Properties of entity TowerStudyComponent.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property TowerId = new Property(1, String.class, "towerId", false, "TOWER_ID");
        public final static Property TowerNo = new Property(2, String.class, "towerNo", false, "TOWER_NO");
        public final static Property GridLineName = new Property(3, String.class, "gridLineName", false, "GRID_LINE_NAME");
        public final static Property ComponentName = new Property(4, String.class, "componentName", false, "COMPONENT_NAME");
    }


    public TowerStudyComponentDao(DaoConfig config) {
        super(config);
    }
    
    public TowerStudyComponentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"t_Tower_StudyComponent\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TOWER_ID\" TEXT," + // 1: towerId
                "\"TOWER_NO\" TEXT," + // 2: towerNo
                "\"GRID_LINE_NAME\" TEXT," + // 3: gridLineName
                "\"COMPONENT_NAME\" TEXT);"); // 4: componentName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"t_Tower_StudyComponent\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TowerStudyComponent entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String towerId = entity.getTowerId();
        if (towerId != null) {
            stmt.bindString(2, towerId);
        }
 
        String towerNo = entity.getTowerNo();
        if (towerNo != null) {
            stmt.bindString(3, towerNo);
        }
 
        String gridLineName = entity.getGridLineName();
        if (gridLineName != null) {
            stmt.bindString(4, gridLineName);
        }
 
        String componentName = entity.getComponentName();
        if (componentName != null) {
            stmt.bindString(5, componentName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TowerStudyComponent entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String towerId = entity.getTowerId();
        if (towerId != null) {
            stmt.bindString(2, towerId);
        }
 
        String towerNo = entity.getTowerNo();
        if (towerNo != null) {
            stmt.bindString(3, towerNo);
        }
 
        String gridLineName = entity.getGridLineName();
        if (gridLineName != null) {
            stmt.bindString(4, gridLineName);
        }
 
        String componentName = entity.getComponentName();
        if (componentName != null) {
            stmt.bindString(5, componentName);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TowerStudyComponent readEntity(Cursor cursor, int offset) {
        TowerStudyComponent entity = new TowerStudyComponent( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // towerId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // towerNo
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // gridLineName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // componentName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TowerStudyComponent entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTowerId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTowerNo(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setGridLineName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setComponentName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TowerStudyComponent entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TowerStudyComponent entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TowerStudyComponent entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
