package com.ew.autofly.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.ew.autofly.db.entity.TowerLocationUpdate;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "t_Tower_Location_update".
*/
public class TowerLocationUpdateDao extends AbstractDao<TowerLocationUpdate, Long> {

    public static final String TABLENAME = "t_Tower_Location_update";

    /**
     * Properties of entity TowerLocationUpdate.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property TowerId = new Property(1, String.class, "towerId", false, "TOWER_ID");
        public final static Property FileUpdateTime = new Property(2, String.class, "fileUpdateTime", false, "FILE_UPDATE_TIME");
        public final static Property GridLineName = new Property(3, String.class, "gridLineName", false, "GRID_LINE_NAME");
        public final static Property TowerNo = new Property(4, String.class, "towerNo", false, "TOWER_NO");
    }


    public TowerLocationUpdateDao(DaoConfig config) {
        super(config);
    }
    
    public TowerLocationUpdateDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"t_Tower_Location_update\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TOWER_ID\" TEXT UNIQUE ," + // 1: towerId
                "\"FILE_UPDATE_TIME\" TEXT," + // 2: fileUpdateTime
                "\"GRID_LINE_NAME\" TEXT," + // 3: gridLineName
                "\"TOWER_NO\" TEXT);"); // 4: towerNo
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"t_Tower_Location_update\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TowerLocationUpdate entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String towerId = entity.getTowerId();
        if (towerId != null) {
            stmt.bindString(2, towerId);
        }
 
        String fileUpdateTime = entity.getFileUpdateTime();
        if (fileUpdateTime != null) {
            stmt.bindString(3, fileUpdateTime);
        }
 
        String gridLineName = entity.getGridLineName();
        if (gridLineName != null) {
            stmt.bindString(4, gridLineName);
        }
 
        String towerNo = entity.getTowerNo();
        if (towerNo != null) {
            stmt.bindString(5, towerNo);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TowerLocationUpdate entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String towerId = entity.getTowerId();
        if (towerId != null) {
            stmt.bindString(2, towerId);
        }
 
        String fileUpdateTime = entity.getFileUpdateTime();
        if (fileUpdateTime != null) {
            stmt.bindString(3, fileUpdateTime);
        }
 
        String gridLineName = entity.getGridLineName();
        if (gridLineName != null) {
            stmt.bindString(4, gridLineName);
        }
 
        String towerNo = entity.getTowerNo();
        if (towerNo != null) {
            stmt.bindString(5, towerNo);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public TowerLocationUpdate readEntity(Cursor cursor, int offset) {
        TowerLocationUpdate entity = new TowerLocationUpdate( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // towerId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // fileUpdateTime
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // gridLineName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // towerNo
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TowerLocationUpdate entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTowerId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setFileUpdateTime(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setGridLineName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTowerNo(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(TowerLocationUpdate entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(TowerLocationUpdate entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(TowerLocationUpdate entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
